---
name: Kaniko Build
on:
  workflow_dispatch:

jobs:
  Build-Kaniko-Image:
    name: Build Kaniko
    uses: stuttgart-things/stuttgart-things/.github/workflows/build-kaniko.yaml@main
    with:
      tag-name: ${{ github.event.inputs.release-tag }}
      environment-name: k8s
      runs-on: arc-runner-scale-set-kaeffken
      dockerfile: ./Dockerfile
      registry: ghcr.io
      repository: stuttgart-things/kaeffken
      image: kaniko-build
      tag: test2
    secrets: inherit
