---
name: Build binaries with goreleaser
on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  Go-Release:
    runs-on: arc-runner-scale-set-kaeffken
    container:
      image: golang:1.21.5
    environment: k8s
    continue-on-error: false
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --skip-validate
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
