---
name: Build binaries with goreleaser
on:
  push:
    #branches:
    #  - main
    tags:
      - '*'

jobs:
  Go-Release:
    runs-on: arc-runner-scale-set-kaeffken
    container:
      image: golang:1.21.5
    environment: k8s
    continue-on-error: false
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          ref: main
          fetch-depth: 0
      - name: Check code
        run: |
          ls -lta
          pwd
          git config --global --add safe.directory /__w/kaeffken/kaeffken
          git checkout main
          git pull
          
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: v1.23.0
          args: release --skip-validate
          workdir: .    
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
