---
name: Build binaries with goreleaser
on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  Go-Release:
    runs-on: arc-runner-scale-set-kaeffken
    permissions:
      contents: write    
    container:
      image: goreleaser/goreleaser:v1.23.0
    environment: k8s
    continue-on-error: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
      - name: Run GoReleaser
        run: |
          ls -lta
          goreleaser check
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
