---
name: Release-Golang
on:
  workflow_dispatch:
    inputs:
      release-tag:
        required: false
        type: string
  push:
    tags:
      - '*'
jobs:
  Create-Git-Tag:
    name: Create Git Tag
    uses: stuttgart-things/stuttgart-things/.github/workflows/git-tag.yaml@main
    if: github.ref_type != 'tag' && github.event.inputs.release-tag != ''
    with:
      tag-name: ${{ github.event.inputs.release-tag }}
      environment-name: k8s
      runs-on: ghr-kaeffken-sthings-cicd
      alpine-version: 3.19.0
      continue-error: false
    secrets: inherit

  Release-Golang-Binaries:
    name: Release Golang
    uses: stuttgart-things/stuttgart-things/.github/workflows/release-golang.yaml@main
    if: always()
    needs: Create-Git-Tag
    with:
      module-name: kaeffken
      environment-name: k8s
      runs-on: ghr-kaeffken-sthings-cicd
      goreleaser-version: v1.23.0
      golang-version: "1.23.1"
    secrets: inherit

  Build-Kaniko-Image:
    name: Build Kaniko
    uses: stuttgart-things/stuttgart-things/.github/workflows/build-kaniko.yaml@main
    if: always()
    needs: Create-Git-Tag
    with:
      environment-name: k8s
      runs-on: ghr-kaeffken-sthings-cicd
      dockerfile: ./Dockerfile
      registry: ghcr.io
      repository: stuttgart-things/kaeffken
      image: kaniko-build
      tag: ${{ github.event.inputs.release-tag }}
    secrets: inherit
