---
name: Build binaries with goreleaser
on:
  push:
    tags:
      - '*'

jobs:
  Go-Release:
    runs-on: arc-runner-scale-set-kaeffken
    container:
      image: golang:1.21.5
    environment: k8s
    continue-on-error: false
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: Check code/git
        run: |
          ls -lta
          printenv
          git config --global --add safe.directory /__w/kaeffken/kaeffken
          git pull
      - name: Release binaries
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: v1.23.0
          args: release --clean
          workdir: .    
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
