---
name: Validate-Golang
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened]

jobs:
  validate-golang:
    name: Valdiate Golang
    uses: stuttgart-things/stuttgart-things/.github/workflows/call-golang-validation.yaml@main
    with:
      module-name: kaeffken
      environment-name: k8s
      runs-on: ghr-kaeffken-skyami-cicd
      golint-version: v1.61.0-alpine
      golang-version: "1.23.1"
      accept-linterrors: true
      accept-failedtests: false
