---
name: Validate-Golang
on:
  #workflow_dispatch:
  push:
    branches:
      - main

jobs:
  Validate-Golang:
    runs-on: arc-runner-scale-set-kaeffken
    container:
      image: golangci/golangci-lint:v1.55
    environment: k8s
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
      - name: Lint code
        run: |
          golangci-lint run

  Test-Golang:
    runs-on: arc-runner-scale-set-kaeffken
    container:
      image: golang:1.21.5
    environment: k8s
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
      - name: Test code
        run: |
          go mod tidy
          go test ./... -v
